listener 1883  # le broker écoute sur le port MQTT standard.
allow_anonymous true  #temporaire. N'importe qui peut se connecter

persistence true   #garde les messages en attente si le broker redémarre.
persistence_location /mosquitto/data/ 
log_dest stdout  #les logs s'affichent dans docker compose logs.